fos_comment:
    db_driver: mongodb
    class:
        model:
            comment: Ltc\CommentBundle\Document\Comment
            thread: Ltc\CommentBundle\Document\Thread
    form:
        comment:
            type: ltc_comment.comment
    service:
        spam_detection:
            comment: fos_comment.spam_detection.comment.akismet
